[package]
name = "chat-demo"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couchbase-lite = { path = "../couchbase-lite", features = ["replication"] }
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "0.2.6", features = ["io-std", "io-util"] }
log = "0.4.8"
env_logger = "0.7"